### ISSUE TITLE
Cudatoolkit and Open3D for conda environment

### ISSUE THREAD

**Issue by saran230420** [yqlbu/jetson-packages-family#1]
Thank you for setting up this repo, it has truly been so helpful. I am trying to install cudatoolkit on my virtual environment (installed via archiconda) and also try to install Open3D 0.1.2. 
I have been trying to get these installed but is this possible or is there a workaround?

**Comment by yqlbu** [comment]
> Thank you for setting up this repo, it has truly been so helpful. I am trying to install cudatoolkit on my virtual environment (installed via archiconda) and also try to install Open3D 0.1.2.
> I have been trying to get these installed but is this possible or is there a workaround?

In my past experience, CUDA should work fine in the conda environment. However, I do recommend do some research on that.
