### ISSUE TITLE
I've successfully  installed python3-matplotlib,but Python3 uses Matplotlib appears in ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by kevinJinm** [yqlbu/jetson-packages-family#2]
This problem occurs when I use the import command.Do you know what caused this? Please help me, thank you.

**Comment by yqlbu** [comment]
> This problem occurs when I use the import command.Do you know what caused this? Please help me, thank you.

Please provide more details (such as screenshots or logs) to reproduce to issue
